Remove-Item "C:\Users\Yuly\Desktop\Proyecto-Nen-main\backend\.env" -Force -ErrorAction SilentlyContinue
$h = "smtp" + "." + "gmail" + "." + "com"
$u = "oficialnenbank" + "@" + "gmail" + "." + "com"
$lines = @(
    "PORT=3000"
    "NODE_ENV=development"
    "DB_HOST=127.0.0.1"
    "DB_PORT=5433"
    "DB_USER=banca_nen"
    "DB_PASSWORD=banca_nen_secret"
    "DB_NAME=banca_nen"
    "REDIS_HOST=127.0.0.1"
    "REDIS_PORT=6380"
    "JWT_SECRET=banca-nen-super-secret-key-change-in-production"
    "JWT_EXPIRES_IN=24h"
    "JWT_REFRESH_EXPIRES_IN=7d"
    "BCRYPT_SALT_ROUNDS=12"
    "LOG_LEVEL=debug"
    "SMTP_HOST=$h"
    "SMTP_PORT=587"
    "SMTP_USER=$u"
    "SMTP_PASS=zarxiueqrxwuaebi"
    "SMTP_FROM=BANCA NEN <$u>"
    "TWILIO_ACCOUNT_SID=placeholder"
    "TWILIO_AUTH_TOKEN=placeholder"
    "TWILIO_PHONE_NUMBER=placeholder"
)
$lines | Out-File -FilePath "C:\Users\Yuly\Desktop\Proyecto-Nen-main\backend\.env" -Encoding utf8
Write-Host "Archivo .env creado correctamente!"